# Generated by Django 5.1.4 on 2025-08-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exerciselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], help_text='Día de la semana para esta rutina', max_length=10, unique=True)),
                ('title', models.CharField(help_text='Título de la rutina del día', max_length=100)),
                ('description', models.TextField(help_text='Descripción detallada de la rutina')),
                ('video_url', models.URLField(help_text='URL del video en GCP Cloud Storage')),
                ('duration', models.PositiveIntegerField(help_text='Duración del video en segundos')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la rutina está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rutina Semanal',
                'verbose_name_plural': 'Rutinas Semanales',
                'ordering': ['day'],
            },
        ),
    ]
