# Generated by Django 5.2.5 on 2025-09-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_userprofile_email_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise_date',
            field=models.DateField(),
        ),
    ]
