# Generated by Django 5.2.5 on 2025-09-17 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_exerciselog_exercise_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Altura en cm', max_digits=5)),
                ('age', models.PositiveIntegerField(help_text='Edad en años')),
                ('waist', models.DecimalField(decimal_places=2, help_text='Cintura en cm', max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, help_text='Cadera en cm', max_digits=5)),
                ('chest', models.DecimalField(decimal_places=2, help_text='Pecho en cm', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measurement_date'],
                'unique_together': {('user', 'measurement_date')},
            },
        ),
    ]
