# Generated by Django 5.2.5 on 2025-09-18 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bodymeasurements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Sexo del usuario', max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='bodymeasurements',
            name='chest',
            field=models.DecimalField(decimal_places=2, help_text='Cuello en cm', max_digits=5),
        ),
        migrations.CreateModel(
            name='BodyCompositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ica', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_composition_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measurement_date'],
                'unique_together': {('user', 'measurement_date')},
            },
        ),
    ]
