# Generated by Django 5.2.5 on 2025-11-06 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_gender_alter_bodymeasurements_chest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(help_text='Fecha de la comida')),
                ('meal_time', models.TimeField(help_text='Hora de la comida')),
                ('meal_type', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack')], help_text='Tipo de comida', max_length=20)),
                ('description', models.TextField(help_text='Descripción de la comida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Diario de Alimentación',
                'verbose_name_plural': 'Entradas de Diario de Alimentación',
                'ordering': ['-meal_date', '-meal_time'],
                'indexes': [models.Index(fields=['user', 'meal_date'], name='app_fooddia_user_id_33e8a0_idx')],
            },
        ),
    ]
