# Generated by Django 5.2.5 on 2025-11-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fooddiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurements',
            name='hip',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cadera en cm', max_digits=5, null=True),
        ),
    ]
