# Generated by Django 5.2.5 on 2025-11-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_make_hip_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hipopresivos',
            field=models.BooleanField(default=False, help_text='Indica si el usuario está inscrito en hipopresivos', verbose_name='Hipopresivos'),
        ),
    ]
