# Generated by Django 5.1.4 on 2025-08-19 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Color del grupo en formato HEX', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de Usuarios',
                'verbose_name_plural': 'Grupos de Usuarios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'Usuario Creado'), ('user_updated', 'Usuario Actualizado'), ('user_deleted', 'Usuario Eliminado'), ('group_created', 'Grupo Creado'), ('group_updated', 'Grupo Actualizado'), ('group_deleted', 'Grupo Eliminado'), ('routine_created', 'Rutina Creada'), ('routine_updated', 'Rutina Actualizada'), ('routine_deleted', 'Rutina Eliminada'), ('video_uploaded', 'Video Subido'), ('video_deleted', 'Video Eliminado')], max_length=20)),
                ('target_model', models.CharField(help_text='Modelo afectado', max_length=50)),
                ('target_id', models.PositiveIntegerField(help_text='ID del objeto afectado')),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad Administrativa',
                'verbose_name_plural': 'Actividades Administrativas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('gcp_bucket', models.CharField(max_length=100)),
                ('gcp_blob_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploading', 'Subiendo'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='uploading', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progreso de subida (0-100)')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Subida de Video',
                'verbose_name_plural': 'Sesiones de Subida de Videos',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='URL del video en GCP Blob Storage')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL de la imagen miniatura', null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duración en segundos')),
                ('assigned_date', models.DateField(help_text='Fecha específica para esta rutina')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_routines', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='admin_panel.usergroup')),
            ],
            options={
                'verbose_name': 'Rutina Personalizada',
                'verbose_name_plural': 'Rutinas Personalizadas',
                'ordering': ['-assigned_date'],
                'unique_together': {('group', 'assigned_date')},
            },
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='admin_panel.usergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de Grupo',
                'verbose_name_plural': 'Membresías de Grupos',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
