# Generated by Django 5.2.5 on 2025-09-09 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_gcp_fields_to_s3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroupmembership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customroutine',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='customroutine',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='customroutine',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='usergroupmembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del video', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción del video')),
                ('filename', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('s3_key', models.CharField(help_text='Clave S3 del video', max_length=500)),
                ('s3_url', models.URLField(help_text='URL pública del video en S3')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL de la imagen miniatura', null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duración en segundos')),
                ('file_size', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
                ('upload_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='admin_panel.videouploadsession')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Orden del video en la rutina (1, 2, 3, etc.)')),
                ('notes', models.TextField(blank=True, help_text='Notas específicas para este video en la rutina')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_videos', to='admin_panel.customroutine')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_assignments', to='admin_panel.video')),
            ],
            options={
                'verbose_name': 'Video de Rutina',
                'verbose_name_plural': 'Videos de Rutina',
                'ordering': ['order'],
                'unique_together': {('routine', 'order')},
            },
        ),
    ]
